server.port=8080
spring.application.name=trajview
spring.threads.virtual.enabled=true

## Logging configuratrion
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.app=DEBUG
logging.file.name=${spring.application.name}.log

#local database
spring.datasource.url=jdbc:mysql://localhost:3306/trajview?createDatabaseIfNotExist=true
#local Gromacs
variables.gmxpath=/usr/bin/gmx

#Dockerdatabase
#spring.datasource.url=jdbc:mysql://db:3306/trajview?createDatabaseIfNotExist=true
#docker Gromacs
#variables.gmxpath=/opt/conda/bin.AVX2_256/gmx

#SinglefileDockerforICE
#spring.datasource.url=jdbc:mysql://172.17.0.2:3306/trajview?createDatabaseIfNotExist=true

jwt.secret="anythingcanbeasecret"


spring.datasource.username=nikhil
spring.datasource.password=nikhil123
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
variables.pythonExecutable=python3
variables.pythonScriptPath=/home/nikhil/Java_Workspace/trajviewBackend/trajectory_service.py



spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Increase the timeout for asynchronous requests (in milliseconds)
server.servlet.session.timeout=3600000
spring.mvc.async.request-timeout=3600000